---

- name: Create system user
  ansible.builtin.user:
    name: "{{ item.name }}"
    comment: "{{ item.comment }}"
    uid: "{{ item.uid }}"
    password: "{{ item.password }}"
    shell: "{{ item.shell }}"
    groups: "{{ item.groups }}"
    state: present
    append: true
    create_home: false
  with_items: "{{ system_user }}"
